### ISSUE TITLE
你好，你hexo cactus博客搜索是怎么弄的，我按照你博客里的配置来弄，搜索直接出现404，请问怎么解决？ 这是我博客:lone0x0.github.io

### ISSUE THREAD

**Issue by ghost** [shipengqi/shipengqi#1]

**Comment by shipengqi** [comment]
@lone0x0 你好，我博客里面写的是以前 [Next 主题](https://theme-next.iissnan.com/getting-started.html) 的配置，Next 主题文档很详细，比较友好，如果你要使用 cactus 主题，配置搜索步骤：

1. `npm install hexo-generator-search --save`  安装 `hexo-generator-search` 插件。可以用来生成索引文件。
2. `hexo new page search` 新建一个 search 页面
3. 修改生成的 `search/index.md` 文件：
    ```
    ---
    title: Search
    type: search
    search: true
    comments: false
    ---
    ```
4. 修改主题配置文件 `_config.md`，在 `nav` 字段下添加 `Search: /search/`：
    ```
    nav:
      ...
      Search: /search/
    ```

**Comment by ghost** [comment]
高版本hexo是无法使用那个插件的，需要把hexo-generator-search/lib/xml_generator.js里的url:
rootURL 改成url: config.root 这样就可以正常使用了。

**Comment by shipengqi** [comment]
嗯，目前我正在从 hexo 迁移到 [hugo](https://github.com/gohugoio/hugo) ，hexo 很久没有用了，所以很多配置可能已经不 work 了。
